CREATE TABLE public.address (
  id BIGINT NOT NULL,
  city VARCHAR(255) NOT NULL,
  contry VARCHAR(255) NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  flat VARCHAR(255) NOT NULL,
  house VARCHAR(255) NOT NULL,
  modified TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  region VARCHAR(255) NOT NULL,
  street VARCHAR(255) NOT NULL,
  CONSTRAINT address_pkey PRIMARY KEY(id)
) ;
